name: ahmoma_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # icon, gift
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  iconsax_flutter: ^1.0.0

  # state management
  flutter_bloc: ^9.1.0

  # logger
  logger: ^2.5.0

  # dio, network
  dio: ^5.8.0+1
  network_info_plus: ^6.1.3
  connectivity_plus: ^6.1.3

  # Firebase, Messaging and notification
  #  firebase_core: ^3.12.1
  #  firebase_messaging: ^15.2.4
  #  firebase_crashlytics: ^4.3.4
  #  flutter_local_notifications: ^19.0.0

  # image, file
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^9.2.1
  flutter_svg: ^2.0.17

  # device
  device_info_plus: ^11.3.3

  # pdf
  syncfusion_flutter_pdf: ^28.2.12

  # sharing
  url_launcher: ^6.3.1
  share_plus: ^10.1.4

  # cached data
  flutter_secure_storage: ^9.2.4
  get_storage: ^2.1.1

  # permission, Cryptography
  permission_handler: ^11.4.0
  crypto: ^3.0.6

  # badge
  app_badge_plus: ^1.2.0

  # internationalization and localization
#  intl: ^0.20.2
  intl: ^0.19.0

  # toast
  fluttertoast: ^8.2.12
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: BeVietNamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 800
